version: '3.8'
services:
  postgis:
    image: postgis/postgis
    container_name: postgis-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ruteo_db
    ports:
      - "5433:5433"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d  # Montar el script aquí

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgis
